language: node_js
node_js:
  - 7
sudo: required
services:
  - neo4j
before_install:
  - curl -H \"Content-Type: application/json\" -X POST -d \'{\"password\":\"$NEO4J_PASS\"}\' -u neo4j:neo4j http://localhost:7474/user/neo4j/password

